# Generated by Django 4.2.4 on 2024-01-26 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
