# Generated by Django 4.2.4 on 2024-01-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0006_appointment_doctor_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_profile_pic',
        ),
    ]
