# Generated by Django 4.2.4 on 2024-01-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_remove_appointment_doctor_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_profile_pic',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='admitDate',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/DoctorProfilePic/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/PatientProfilePic/'),
        ),
    ]
