# Generated by Django 4.2.4 on 2024-01-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0008_remove_appointment_patient_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/PatientProfilePic/'),
        ),
    ]
